application: x8-euphoric-hull-j 
version: 1
runtime: go
api_version: go1

builtins:
- remote_api: on

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/remote_api
  script: _go_app
  login: admin
  
- url: /.*
  script: _go_app
